version: '3'

services:
  local_nginx:
    build: ./docker/nginx
    container_name: local_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/app
    depends_on:
      - local_php

  local_php:
    build: ./docker/php-fpm
    container_name: local_php
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - local_mysql

  local_mysql:
    image: mysql:5.7
    container_name: local_mysql
    restart: unless-stopped
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-local_db}
      MYSQL_USER: ${DB_USERNAME:-local}
      MYSL_PASSWORD: ${DB_PASSWORD:-11111111}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
