version: '3'

services:
  local_web_server:
    build: ./docker/nginx
    container_name: local_web_server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/app
    depends_on:
      - local_app

  local_app:
    build:
      context: ./docker/php-fpm
      args:
        USERNAME: ${USERNAME:-local}
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    container_name: local_app
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - local_db

  local_db:
    image: mysql:8
    container_name: local_db
    restart: unless-stopped
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-local_db}
      MYSQL_USER: ${DB_USERNAME:-local}
      MYSL_PASSWORD: ${DB_PASSWORD:-11111111}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
